name: Lint & Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      
      - name: 'Yarn install'
        run: |
          yarn
      - name: 'Lint'
        run: |
          yarn build
